application: kinetic-hydra-838
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js
  
- url: /bower_components
  static_dir: bower_components

- url: /.*
  script: happypet.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest